baseURL = 'http://childinclusionfund.com/'
languageCode = 'en-us'
title = 'Child Inclusion Fund'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Child Inclusion Fund"
  favicon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  # site_logo = "images/logo.svg"
  recent_posts_number = 2
  custom_css = ["custom.css"]
  cover_dimming_class = 'custom-cover'

# 
[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/childinclusionfund"
color = "#fefefe"
